accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts.views import Login_View, RegisterView

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', Login_View.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='accounts/logout.html'), name="logout"),
    ]

api/urls.py
from django.urls import path

from api import views

app_name = 'api'

urlpatterns = [
    path('categories_list', views.CategoriesListAndCreateAPIView.as_view(), name='categories_list'),  # noqa
    path('category_update/<id>', views.CategoryDetailUpdateDeleteAPIView.as_view(), name='category_update'),  # noqa

    path('expenses_list', views.ExpensesListAndCreateAPIView.as_view(), name='expenses_list'),  # noqa
    path('expense_update/<id>', views.ExpenseDetailUpdateDeleteAPIView.as_view(), name='expense_update'),  # noqa

    path('income_list', views.IncomeListAndCreateAPIView.as_view(), name='income_list'),  # noqa
    path('income_update/<id>', views.IncomeDetailUpdateDeleteAPIView.as_view(), name='income_update'),  # noqa
]

budget/urls.py
from django.urls import path

from . import views

app_name = 'budget'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('categories_list/', views.CategoriesListView.as_view(), name='categories_list'),  # noqa
    path('category_create/', views.CategoryCreateView.as_view(), name='category_create'),  # noqa
    path('category_update/<int:id>', views.CategoryUpdateView.as_view(), name='category_update'),  # noqa
    path('category_delete/<int:id>', views.CategoryDeleteView.as_view(), name='category_delete'),  # noqa

    path('expenses_list/', views.ExpensesListView.as_view(), name='expenses_list'),  # noqa
    path('expense_create/', views.ExpenseCreateView.as_view(), name='expense_create'),  # noqa
    path('expense_update/<int:id>', views.ExpenseUpdateView.as_view(), name='expense_update'),  # noqa
    path('expense_delete/<int:id>', views.ExpenseDeleteView.as_view(), name='expense_delete'),  # noqa

    path('income_list/', views.IncomeListView.as_view(), name='income_list'),
    path('income_create/', views.IncomeCreateView.as_view(), name='income_create'),  # noqa
    path('income_update/<int:id>', views.IncomeUpdateView.as_view(), name='income_update'),  # noqa
    path('income_delete/<int:id>', views.IncomeDeleteView.as_view(), name='income_delete'),  # noqa
]

budgeting_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    # Apps
    path('accounts/', include('accounts.urls')),
    path('budget/', include('budget.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

      <!-- Project CSS -->
      <link rel="stylesheet" type="text/css" href="{% static 'budget/css/style.css' %}">

  </head>

  <body>

        <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light navbar-dark bg-dark ">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Hello, {{ user.username }}!</a>
                    </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      User
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'accounts:register' %}">Register</a>
                        <a class="dropdown-item" href="{% url 'accounts:login' %}">Log in</a>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'budget:index' %}"> Home</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Categories
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'budget:categories_list' %}">List of categories</a>
                        <a class="dropdown-item" href="{% url 'budget:category_create' %}"> Add new Category</a>
                        <a class="dropdown-item" href="{% url 'budget:category_update' id=1 %}"> Update existing Category [id]</a>
                        <a class="dropdown-item" href="{% url 'budget:category_delete' id=1 %}"> Delete existing Category [id]</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Expenses
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'budget:expenses_list' %}">List of Expenses</a>
                        <a class="dropdown-item" href="{% url 'budget:expense_create' %}">Add new Expense</a>
                        <a class="dropdown-item" href="{% url 'budget:expense_update' id=1 %}">Update existing Expense [id]</a>
                        <a class="dropdown-item" href="{% url 'budget:expense_delete' id=1 %}">Delete existing Expense [id]</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Income
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'budget:income_list' %}">List of Income</a>
                        <a class="dropdown-item" href="{% url 'budget:income_create' %}">Add new Income</a>
                        <a class="dropdown-item" href="{% url 'budget:income_update' id=1 %}">Update existing Income [id]</a>
                        <a class="dropdown-item" href="{% url 'budget:income_delete' id=1 %}">Delete existing Income [id]</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      API
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'api:categories_list' %}">Categories List</a>
                        <a class="dropdown-item" href="{% url 'api:category_update' id=1%}">Category Update [id]</a>
                        <a class="dropdown-item" href="{% url 'api:expenses_list' %}">Expenses List</a>
                        <a class="dropdown-item" href="{% url 'api:expense_update' id=1%}">Expense Update [id]</a>
                        <a class="dropdown-item" href="{% url 'api:income_list' %}">Income List</a>
                        <a class="dropdown-item" href="{% url 'api:income_update' id=1%}">Income Update [id]</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
{% block content %}{% endblock content %}
  </body>
</html>